// import {
//   faCalendarCheck,
//   faChartLine,
//   faExclamation,
//   faHandHoldingDollar,
//   faHandshake,
//   faHeadset,
//   faMagnifyingGlass,
//   faScrewdriverWrench,
//   faToolbox,
//   faUserSecret,
//   faUserTie,
// } from '@fortawesome/free-solid-svg-icons';
import {
  AttendanceScreen,
  ChargeScreen,
  CustomerScreen,
  DirectionScreen,
  EquipmentScreen,
  PendencieScreen,
  SaleScreen,
  ScheduleScreen,
  SinisterScreen,
  SumaryScreen,
  SupervisionScreen,
} from '../screens';

export const ROUTES_PATHS = [
  {
    path: 'Atendimento',
    element: AttendanceScreen,
    title: 'Atendimento',
    isPrivate: true,
    Permissions: [],
  },
  {
    path: 'Clientes',
    element: CustomerScreen,
    title: 'Clientes',
    isPrivate: true,
    Permissions: [],
  },
  {
    path: 'Vendas',
    element: SaleScreen,
    title: 'Vendas',
    isPrivate: true,
    Permissions: [],
  },
  {
    path: 'Pendencias',
    element: PendencieScreen,
    title: 'Pendencias',
    isPrivate: true,
    Permissions: [],
  },
  {
    path: 'Sinistros',
    element: SinisterScreen,
    title: 'Sinistros',
    isPrivate: true,
    Permissions: [],
  },
  {
    path: 'Cobrancas',
    element: ChargeScreen,
    title: 'Cobrancas',
    isPrivate: true,
    Permissions: [],
  },
  {
    path: 'Agenda',
    element: ScheduleScreen,
    title: 'Agenda',
    isPrivate: true,
    Permissions: [],
  },
  {
    path: 'Equipamentos',
    element: EquipmentScreen,
    title: 'Equipamentos',
    isPrivate: true,
    Permissions: [],
  },
  {
    path: 'Supervisao',
    element: SupervisionScreen,
    title: 'Supervisao',
    isPrivate: true,
    Permissions: [],
  },
  {
    path: 'Diretoria',
    element: DirectionScreen,
    title: 'Diretoria',
    isPrivate: true,

    Permissions: [],
  },

  {
    path: 'Sumario ',
    element: SumaryScreen,
    title: 'Sumario',
    isPrivate: true,
    Permissions: [],
  },
];
